document.addEventListener('DOMContentLoaded', function () {
    const toolList = document.getElementById('tool-list');

    // Define an array of cybersecurity tools.
    const tools = [
        {
            name: "OWASP ZAP",
            description: "The OWASP Zed Attack Proxy (ZAP) is one of the world’s most popular free security tools and is actively maintained by a dedicated international team of volunteers. Great for pen-testers, devs, QA, and CI/CD integration."
        },
        {
            name: "Snort",
            description: "Snort is an open-source, free and lightweight network intrusion detection system (NIDS) software for Linux and Windows to detect emerging threats."
        },
        {
            name: "Metasploit",
            description: "Metasploit is the world’s most used penetration testing software. Uncover weaknesses in your defenses, focus on the highest risks, and improve your security outcomes."
        },
      {
           name: "Torghost",
           description: "TorGhost is an anonymization script. TorGhost redirects all internet traffic through SOCKS5 tor proxy. DNS requests are also redirected via tor, thus preventing DNSLeak. The scripts also disables unsafe packets exiting the system. Some packets like ping request can compromise your identity."
      },
      {
           name: "DarkFly",
           description: "DarkFly-Tool is an installation tool for installing tools. this tool makes it easy for you. so you don't need to type git clone or look for the github repository. You only have to choose the number. which tool you want to install. there are 530 tools ready for intall. and for those of you who like to have fun. there are 7 SMS spam tools that are ready to use, you just need to choose spam to use the target number. there is a tocopedia DLL",
      },
  {
       name: "Tool-X",
       description: "Tool-X is a Kali Linux hacking tools installer for Termux and linux system.It's the most advanced hacking ,From this you do lots of stuffs .WARNING:USE AT YOUR OWN RISK"
  },
      {
         name: "Zphisher",
         description: "Zphisher is a powerful open-source tool Phishing Tool. It became very popular nowadays and is used to do phishing attacks on Target. Zphisher is easier than Social Engineering Toolkit. It contains some templates generated by a tool called Zphisher and offers phishing templates webpages for 33 popular sites such as Facebook, Instagram, Google, Snapchat, GitHub, Yahoo, Proton mail, Spotify, Netflix, LinkedIn, WordPress, Origin, Steam, Microsoft, etc. It also provides an option to use a custom template if someone wants. This tool makes it easy to perform a phishing attack. Using this tool you can perform phishing in (wide area network). This tool can be used to get credentials such as id, password.WARNING:  This Tool is made for educational purpose only ! Author will not be responsible for any misuse of this toolkit ! "
      },
    {
       name: "Sociel-Engineering Toolkit",
       description: "The Social-Engineer Toolkit (SET) is an open-source penetration testing framework designed for social engineering. SET has a number of custom attack vectors that allow you to make a believable attack in a fraction of time. These kind of tools use human behaviors to trick them to the attack vectors."
    },
      {
          name: "Nmap",
          description: "Nmap (Network Mapper) is a network scanner created by Gordon Lyon (also known by his pseudonym Fyodor Vaskovich). Nmap is used to discover hosts and services on a computer network by sending packets and analyzing the responses. Nmap provides a number of features for probing computer networks, "
      },
      {
          name: "Ubuntu-In-Termux",
          description: "Ubuntu-In-Termux is a Termux Power Tool which allows Root access to the users without rooting the device"
      }
    ];

    // Populate the tool list.
    tools.forEach(tool => {
        const listItem = document.createElement('li');
        listItem.innerHTML = `
            <h2>${tool.name}</h2>
            <p>${tool.description}</p>
            <a href="https://github.com/search?q=${tool.name}" target="_blank">View on GitHub</a>
        `;
        toolList.appendChild(listItem);
    });
});
const menuIcon = document.querySelector(".menu-icon");
const navLinks = document.querySelector(".nav-links");

menuIcon.addEventListener("click", () => {
  navLinks.classList.toggle("nav-active");
});
